### ISSUE TITLE
mclust library issue

### ISSUE THREAD

**Issue by ansariom** [mahmoudibrahim/JAMM#5]
I ran the JAMM.sh successfully before but now that I am trying to run the same script I get the following error:
Calls: initparam ... lapply -> FUN -> me -> eval -> eval -> meV -> .Fortran
Execution halted

I updated mclust package and it didn't work. 
How can I resolve this issue?

Thanks!

**Comment by mahmoudibrahim** [comment]
Thanks for letting me know..I will look into this over the next few days.

can you please let me know which version of R you're using and which
version of mclust?

thanks!

**Comment by mahmoudibrahim** [comment]
I verified that JAMM is working with R version 3.4.3, mclust version 5.4.3 and with R version 3.5.3 and mclust version 5.4.3. So I'm closing this issue.

**Comment by axol0tl** [comment]
trying to creacte conda env for jamm in 2023. got this message:
Could not solve for environment specs
The following packages are incompatible
├─ r-base 3.5.3**  is requested and can be installed;
└─ r-mclust 5.4.3**  is uninstallable because it requires
   └─ r-base >=3.5.1,<3.5.2.0a0 , which conflicts with any installable versions previously reported.
 
Tried with:
r-base                    3.5.1
r-mclust                  5.4.3           
r-signal                  0.7_6

and it also works
